### ISSUE TITLE
Font build failure with recent fontmake (3.10.0)

### ISSUE THREAD

**Issue by hosiet** [etunni/arapey#8]
Hi, the arapey font build will fail with the recent version of fontmake:

```bash
-> % which python
/dev/shm/venv/bin/python

-> % python -m fontmake --version
3.10.0

-> % python -m fontmake -g ./src/Arapey-VF-pro-NOV.glyphs -o variable --output-path .
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib.builder:Running 'propagate_all_anchors' transformation
Traceback (most recent call last):
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/smart_components.py", line 64, in variation_model
    model = VariationModel(master_locations, axisOrder=axis_order, extrapolate=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/fontTools/varLib/models.py", line 263, in __init__
    raise VariationModelError("Locations must be unique.")
fontTools.varLib.errors.VariationModelError: Locations must be unique.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/dev/shm/venv/lib/python3.12/site-packages/fontmake/__main__.py", line 761, in <module>
    sys.exit(main())
             ^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/fontmake/__main__.py", line 708, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/dev/shm/venv/lib/python3.12/site-packages/fontmake/font_project.py", line 910, in run_from_glyphs
    designspace = self.build_master_ufos(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/fontmake/font_project.py", line 246, in build_master_ufos
    designspace = glyphsLib.to_designspace(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/__init__.py", line 161, in to_designspace
    return builder.designspace
           ^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/builders.py", line 337, in designspace
    list(self.masters)  # Make sure that the UFOs are built
    ^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/builders.py", line 214, in masters
    self.to_ufo_layers()  # below!
    ^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/builders.py", line 279, in to_ufo_layers
    self.to_ufo_glyph(ufo_glyph, layer, glyph)  # .glyph
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/glyph.py", line 196, in to_ufo_glyph
    self.to_ufo_components(ufo_glyph, layer)  # .components
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/components.py", line 78, in to_ufo_components
    to_ufo_smart_component(self, layer, component, pen)
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/smart_components.py", line 118, in to_ufo_smart_component
    model = variation_model(root, masters, layer)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/venv/lib/python3.12/site-packages/glyphsLib/builder/smart_components.py", line 69, in variation_model
    raise ValueError(
ValueError: Could not generate smart component model for _part.barcurrency used in <GSLayer "Black" (cedi)>.
Locations were:
  Black = {'LARGO': 0.0}
  short = {'LARGO': 0.0}
  long = {'LARGO': 1.0}

-> % pip list
Package             Version
------------------- -----------
absl-py             2.1.0
afdko               4.0.2
appdirs             1.4.4
attrs               24.2.0
axisregistry        0.4.11
babelfont           3.1.2
beautifulsoup4      4.12.3
booleanOperations   0.9.0
Brotli              1.1.0
bump2version        1.0.1
bumpfontversion     0.4.1
cattrs              24.1.2
certifi             2024.8.30
cffi                1.17.1
cffsubr             0.3.0
charset-normalizer  3.4.0
compreffor          0.5.6
cryptography        44.0.0
defcon              0.10.3
Deprecated          1.2.15
font-v              2.1.0
fontFeatures        1.8.0
fontmake            3.10.0
fontMath            0.9.4
fontParts           0.12.3
fontPens            0.2.4
fonttools           4.55.2
fs                  2.4.16
gflanguages         0.7.1
gfsubsets           2024.9.25
gftools             0.9.76
gitdb               4.0.11
GitPython           3.1.43
glyphsets           1.0.0
glyphsLib           6.9.5
idna                3.10
importlib_resources 6.4.5
Jinja2              3.1.4
lxml                5.3.0
markdown-it-py      3.0.0
MarkupSafe          3.0.2
mdurl               0.1.2
MutatorMath         3.0.1
nanoemoji           0.15.1
networkx            3.4.2
ninja               1.11.1.2
openstep_plist      0.4.0
opentype-sanitizer  9.2.0
orjson              3.10.12
packaging           24.2
picosvg             0.22.1
pillow              11.0.0
pip                 24.3.1
pngquant-cli        3.0.3
protobuf            3.20.3
pyclipper           1.3.0.post6
pycparser           2.22
pygit2              1.15.0
PyGithub            2.5.0
Pygments            2.18.0
PyJWT               2.10.1
PyNaCl              1.5.0
pyparsing           3.2.0
python-dateutil     2.9.0.post0
PyYAML              6.0.2
regex               2024.11.6
requests            2.32.3
resvg-cli           0.44.0
rich                13.9.4
ruamel.yaml         0.18.6
ruamel.yaml.clib    0.2.12
setuptools          75.6.0
six                 1.17.0
skia-pathops        0.8.0.post2
smmap               5.0.1
soupsieve           2.6
statmake            0.6.0
strictyaml          1.7.3
tabulate            0.9.0
toml                0.10.2
tqdm                4.67.1
ttfautohint-py      0.5.1
typing_extensions   4.12.2
ufo2ft              3.3.1
ufoLib2             0.17.0
ufomerge            1.8.2
ufonormalizer       0.6.2
ufoProcessor        1.13.3
uharfbuzz           0.43.0
unicodedata2        15.1.0
Unidecode           1.3.8
urllib3             2.2.3
vharfbuzz           0.3.1
vttLib              0.12.0
wrapt               1.17.0
zopfli              0.2.3.post1
```

**Comment by etunni** [comment]
Hello, if you want to use the font, you have static and variable fonts at this link:
https://github.com/etunni/arapey/tree/master/fonts

**Comment by hosiet** [comment]
Thanks, I am aware of prebuilt fonts. That being said, being unable to generate these font files from .glyphs is still a bug and can be fixed.

**Comment by etunni** [comment]
> Thanks, I am aware of prebuilt fonts. That being said, being unable to generate these font files from .glyphs is still a bug and can be fixed.

I think that problem become from smart components have incompatibility with fontmake
I'll try to generate the font files directly from glyphsapp.
